### ISSUE TITLE
Regarding the Challenge

### ISSUE THREAD

**Issue by frndz** [RealImage/challenge2016#1]
May I know the website link of this challenge where I can find all the details about the challenge including Prize, challenge end date, winner announcement etc ???

**Comment by sudhirj** [comment]
This is the only website that we use for this - extra details are as follows:

3 solutions that we choose will receive Amazon gift cards worth Rs. 25,000 each. There is no closing date - the gift cards will be awarded as and when we see excellent solutions, so the prizes are first come first served.

**Comment by frndz** [comment]
I am not convinced. I mean how should I believe. There is no proper website where the complete details are mentioned.
Anyone can put a problem statement in Github for his PERSONAL use case and ask to submit solution.

How can a person who have submitted a solution claim about his/her prize, no closing date, no detail/proof of the contest, organizers.

What if I submit my solution, your purpose got fulfilled and you say that the solution is not proper. Then, you got your job done without spending a rupee ??

**Comment by sudhirj** [comment]
Participation in the contest is entirely voluntary - we don't compel anyone to participate, and a lot of the participants have already seen and might know the winners of last year's competition. 

With regards to this point

> What if I submit my solution, your purpose got fulfilled and you say that the solution is not proper. Then, you got your task done without spending a rupee.

We don't ask to license your code - you maintain copyright over it. The actual business problem is much more complicated, and we've already solved it and applied for patents internationally, so I don't think we'll need to steal solutions from participants :D

**Comment by frndz** [comment]
So, where can I find last year's winner's details ??

**Comment by sudhirj** [comment]
https://github.com/RealImage/gophercon/pulls?q=is%3Apr+is%3Aclosed
